events {}

http {

    server {

        listen 80;

        location /api/auth/ {
            proxy_pass http://auth-service:8000/;
        }

        location /api/account/ {
            proxy_pass http://ledger-service:5000/api/v1/account/;
        }

    }

}
