apiVersion: apps/v1
kind: Deployment
metadata:
  name: vaultline-api
spec:
  replicas: 2
  selector:
    matchLabels:
      app: vaultline-api
  template:
    metadata:
      labels:
        app: vaultline-api
    spec:
      imagePullSecrets:      
      - name: regcred
      containers:
      - name: api
        image: awi2005/vaultline-api:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 5000
        # ADD THIS BLOCK TO FIX THE WARNINGS
        resources:
          requests:
            memory: "64Mi"   # Minimum guaranteed RAM
            cpu: "100m"      # 10% of a CPU core
          limits:
            memory: "128Mi"  # Hard cap to prevent memory leaks
            cpu: "250m"      # Hard cap to prevent CPU hogging
---
apiVersion: v1
kind: Service
metadata:
  name: vaultline-api-service
spec:
  selector:
    app: vaultline-api
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000