apiVersion: apps/v1
kind: Deployment
metadata:
  name: vaultline-web
  namespace: default
spec:
  replicas: 2
  selector:
    matchLabels:
      app: vaultline-web
  template:
    metadata:
      labels:
        app: vaultline-web
    spec:
      containers:
      - name: web
        image: awi2005/vaultline-web:latest
        ports:
        - containerPort: 80
        # ADDED: Resource Requests and Limits for Stability
        resources:
          requests:
            memory: "64Mi"
            cpu: "100m"
          limits:
            memory: "128Mi"
            cpu: "200m"
        env:
        - name: API_URL
          value: "http://127.0.0.1:5000"